# Generated by Django 5.2.8 on 2025-12-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia')], max_length=20, verbose_name='Método de pago'),
        ),
    ]
