# Generated by Django 5.2.8 on 2025-12-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_userprofile_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('morning', 'Mañana (8:00 AM - 12:00 PM)'), ('afternoon', 'Tarde (12:00 PM - 6:00 PM)'), ('evening', 'Noche (6:00 PM - 9:00 PM)')], max_length=50, verbose_name='Hora de entrega'),
        ),
    ]
