# Generated by Django 5.2.8 on 2025-12-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
