# Generated by Django 5.2.8 on 2025-12-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_userprofile_verification_token_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de cancelación'),
        ),
    ]
