# Generated by Django 5.2.8 on 2025-12-21 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_cart_updated_at_alter_category_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(max_length=100, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Municipio'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '⭐ 1 - Muy malo'), (2, '⭐⭐ 2 - Malo'), (3, '⭐⭐⭐ 3 - Regular'), (4, '⭐⭐⭐⭐ 4 - Bueno'), (5, '⭐⭐⭐⭐⭐ 5 - Excelente')], db_index=True, verbose_name='Calificación')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título del review')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('is_verified_purchase', models.BooleanField(db_index=True, default=False, verbose_name='Compra verificada')),
                ('is_approved', models.BooleanField(db_index=True, default=True, help_text='El admin puede moderar reviews inapropiados', verbose_name='Aprobado')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Votos útiles')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product', verbose_name='Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='shop.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto de utilidad',
                'verbose_name_plural': 'Votos de utilidad',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Lista de Deseos',
                'verbose_name_plural': 'Listas de Deseos',
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notify_price_drop', models.BooleanField(default=True, verbose_name='Notificar bajada de precio')),
                ('notify_back_in_stock', models.BooleanField(default=True, verbose_name='Notificar cuando esté disponible')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio al agregar')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Producto')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.wishlist', verbose_name='Wishlist')),
            ],
            options={
                'verbose_name': 'Item de Wishlist',
                'verbose_name_plural': 'Items de Wishlist',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'is_approved', '-created_at'], name='shop_review_product_bf7cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-created_at'], name='shop_review_user_id_6a0a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating', 'is_approved'], name='shop_review_rating_66e43c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('product', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpful',
            unique_together={('review', 'user')},
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['wishlist', 'product'], name='shop_wishli_wishlis_97a0a8_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['product', '-added_at'], name='shop_wishli_product_1b205b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'product')},
        ),
    ]
