# Generated by Django 5.2.8 on 2025-12-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_order_delivery_city_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Color principal del producto', max_length=50, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensiones',
            field=models.CharField(blank=True, help_text='Ej: 10cm x 5cm x 2cm, Largo 50cm', max_length=200, verbose_name='Dimensiones'),
        ),
        migrations.AddField(
            model_name='product',
            name='garantia',
            field=models.CharField(blank=True, help_text='Ej: 1 año, 6 meses, Sin garantía', max_length=100, verbose_name='Garantía'),
        ),
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.CharField(blank=True, help_text='Fabricante o marca del producto', max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='Ej: Acero galvanizado, Plástico ABS, Madera', max_length=100, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kilogramos', max_digits=8, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='potencia',
            field=models.CharField(blank=True, help_text='Ej: 1500W, 2HP, 750W', max_length=50, verbose_name='Potencia'),
        ),
        migrations.AddField(
            model_name='product',
            name='uso_recomendado',
            field=models.TextField(blank=True, help_text='Para qué se recomienda usar este producto', verbose_name='Uso Recomendado'),
        ),
        migrations.AddField(
            model_name='product',
            name='voltaje',
            field=models.CharField(blank=True, help_text='Ej: 110V, 220V, 12V DC', max_length=50, verbose_name='Voltaje'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['marca', 'is_active'], name='shop_produc_marca_6dc832_idx'),
        ),
    ]
